"""
Deterministic Post-Generation Reconstructor
Calculates exact running balances and enforces tier caps 
on the raw events generated by the TVAE model.
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime, date
from pathlib import Path
from typing import Dict, Optional, Tuple

import pandas as pd
import numpy as np

logger = logging.getLogger(__name__)

# Tier-specific balance caps (KES) - CBK PG/43 guidelines
TIER_CAPS = {
    1: 50_000.0,
    2: 200_000.0,
    3: 1_000_000.0,
    4: 5_000_000.0,
}

# Tier-specific daily velocity caps (KES) - CBK PG/43 cumulative daily limits
DAILY_VELOCITY_CAPS = {
    1: 25_000.0,
    2: 100_000.0,
    3: 500_000.0,
    4: 10_000_000.0,
}


@dataclass
class ConstraintStats:
    """Statistics for constraint enforcement during balance reconstruction."""
    total_transactions: int = 0
    accepted_transactions: int = 0
    rejected_insufficient_funds: int = 0
    rejected_tier_cap_violation: int = 0
    rejected_daily_velocity_cap: int = 0
    ledger_continuity_failures: int = 0


@dataclass
class CustomerBalanceState:
    """Track balance state for each customer during reconstruction."""
    customer_id: str
    tier: int
    balance: float
    daily_outflow_total: float = 0.0
    last_reset_date: Optional[date] = None


class BalanceReconstructor:
    """
    Reconstructs deterministic balances from TVAE-generated raw events.
    
    Takes TVAE raw events (8 columns) as input:
    - customer_id, tier, archetype, transaction_type, amount, timestamp, direction, is_international
    
    Groups by customer_id and sorts by timestamp, then:
    - Sets initial balance from customer profiles or default range
    - Iteratively calculates running balance based on direction (inflow/outflow)
    - Enforces tier-specific balance caps (Tier 1: 50K, Tier 2: 200K, Tier 3: 1M, Tier 4: 5M)
    - Rejects transactions that would violate tier caps
    - Enforces daily velocity caps for outflows
    
    Outputs balance-corrected events (9 columns) to data/tvae_balance_corrected_{partition}.parquet
    """
    
    def __init__(
        self,
        customer_profiles_path: Optional[str] = None,
        initial_balance_range: Tuple[float, float] = (500.0, 5000.0),
        output_dir: str = "data",
    ):
        """
        Initialize the BalanceReconstructor.
        
        Args:
            customer_profiles_path: Path to customer profiles CSV for initial balances
            initial_balance_range: Default (min, max) range for initial balances if no profiles
            output_dir: Directory for output parquet files
        """
        self.customer_profiles_path = customer_profiles_path
        self.initial_balance_range = initial_balance_range
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        self.stats = ConstraintStats()
        self.customer_states: Dict[str, CustomerBalanceState] = {}
        
    def _load_initial_balances(self, df: pd.DataFrame) -> Dict[str, float]:
        """Load initial balances from customer profiles or use default range."""
        initial_balances = {}
        
        if self.customer_profiles_path and Path(self.customer_profiles_path).exists():
            try:
                profiles_df = pd.read_csv(self.customer_profiles_path)
                for row in profiles_df.itertuples():
                    cid = row.customer_id
                    opening = getattr(row, 'initial_balance_kes', 
                                     getattr(row, 'opening_balance', 
                                            np.random.uniform(*self.initial_balance_range)))
                    initial_balances[cid] = float(opening)
                logger.info(f"Loaded {len(initial_balances)} initial balances from profiles")
            except Exception as e:
                logger.warning(f"Failed to load customer profiles: {e}. Using default range.")
        
        # Fill missing customers with default range
        unique_customers = df['customer_id'].unique()
        for cid in unique_customers:
            if cid not in initial_balances:
                initial_balances[cid] = np.random.uniform(*self.initial_balance_range)
        
        logger.info(f"Initialized {len(initial_balances)} customer balances")
        return initial_balances
    
    def _reset_daily_velocity(self, state: CustomerBalanceState, tx_date: date) -> None:
        """Reset daily outflow counter if we've moved to a new day."""
        if state.last_reset_date is None:
            state.last_reset_date = tx_date
            return
        if tx_date != state.last_reset_date:
            state.daily_outflow_total = 0.0
            state.last_reset_date = tx_date
    
    def _validate_transaction(
        self,
        state: CustomerBalanceState,
        amount: float,
        direction: str,
        tx_date: date,
    ) -> Tuple[bool, Optional[str]]:
        """
        Validate a transaction against all constraints.
        
        Returns:
            (is_valid, rejection_reason)
        """
        tier_cap = TIER_CAPS.get(state.tier, TIER_CAPS[1])
        daily_cap = DAILY_VELOCITY_CAPS.get(state.tier, DAILY_VELOCITY_CAPS[1])
        
        # Reset daily velocity if new day
        self._reset_daily_velocity(state, tx_date)
        
        # Calculate proposed balance
        if direction == "outflow":
            new_balance = state.balance - amount
            
            # Check insufficient funds
            if new_balance < 0:
                return False, "insufficient_funds"
            
            # Check daily velocity cap for outflows
            if state.daily_outflow_total + amount > daily_cap:
                return False, "daily_velocity_cap"
                
        elif direction == "inflow":
            new_balance = state.balance + amount
        else:
            # Default to outflow for unknown directions
            new_balance = state.balance - amount
            if new_balance < 0:
                return False, "insufficient_funds"
        
        # Check tier cap violation
        if new_balance > tier_cap:
            return False, "tier_cap_violation"
        
        return True, None
    
    def reconstruct(
        self,
        df: pd.DataFrame,
        partition: str = "default",
    ) -> pd.DataFrame:
        """
        Reconstruct deterministic balances from TVAE raw events.
        
        Args:
            df: DataFrame with 8 TVAE columns (customer_id, tier, archetype, 
               transaction_type, amount, timestamp, direction, is_international)
            partition: Partition identifier for output file naming
        
        Returns:
            DataFrame with 9 columns (original 8 + balance)
        """
        logger.info(f"Starting balance reconstruction for {len(df)} transactions")
        logger.info(f"Input columns: {df.columns.tolist()}")
        logger.info(f"Input shape: {df.shape}")
        
        self.stats = ConstraintStats()
        self.stats.total_transactions = len(df)
        
        # Load initial balances
        initial_balances = self._load_initial_balances(df)
        
        # Sort chronologically by customer_id then timestamp
        df_sorted = df.sort_values(by=['customer_id', 'timestamp']).copy()
        
        valid_transactions = []
        
        # Initialize customer states
        for cid in df_sorted['customer_id'].unique():
            # Get the first row for this customer
            customer_df = df_sorted[df_sorted['customer_id'] == cid]
            # Ensure we have a DataFrame, not a Series
            if isinstance(customer_df, pd.Series):
                tier = int(customer_df['tier'])
            else:
                tier = int(customer_df.iloc[0]['tier'])
            self.customer_states[cid] = CustomerBalanceState(
                customer_id=cid,
                tier=tier,
                balance=initial_balances[cid],
            )
        
        # Process transactions
        for row in df_sorted.itertuples():
            cid = row.customer_id
            state = self.customer_states[cid]
            amount = float(row.amount)
            direction = str(row.direction)
            
            # Parse timestamp for daily velocity tracking
            if isinstance(row.timestamp, str):
                tx_date = pd.to_datetime(row.timestamp).date()
            else:
                tx_date = row.timestamp.date()
            
            # Validate transaction
            is_valid, rejection_reason = self._validate_transaction(
                state, amount, direction, tx_date
            )
            
            if not is_valid:
                # Update rejection statistics
                if rejection_reason == "insufficient_funds":
                    self.stats.rejected_insufficient_funds += 1
                elif rejection_reason == "tier_cap_violation":
                    self.stats.rejected_tier_cap_violation += 1
                elif rejection_reason == "daily_velocity_cap":
                    self.stats.rejected_daily_velocity_cap += 1
                continue
            
            # Apply transaction
            if direction == "outflow":
                state.balance -= amount
                state.daily_outflow_total += amount
            else:
                state.balance += amount
            
            state.balance = round(state.balance, 2)
            
            # Convert row to dict and add balance
            row_dict = row._asdict()
            if hasattr(row_dict, 'Index'):
                del row_dict['Index']
            row_dict = dict(row._asdict()) if hasattr(row, '_asdict') else {
                'customer_id': row.customer_id,
                'tier': row.tier,
                'archetype': row.archetype,
                'transaction_type': row.transaction_type,
                'amount': row.amount,
                'timestamp': row.timestamp,
                'direction': row.direction,
                'is_international': row.is_international,
            }
            row_dict['balance'] = state.balance
            
            valid_transactions.append(row_dict)
            self.stats.accepted_transactions += 1
        
        result_df = pd.DataFrame(valid_transactions)
        
        # Validate ledger continuity
        self._validate_ledger_continuity(result_df)
        
        # Log statistics
        self._log_constraint_stats()
        
        # Save to parquet
        output_path = self.output_dir / f"tvae_balance_corrected_{partition}.parquet"
        result_df.to_parquet(output_path, index=False)
        logger.info(f"Saved {len(result_df)} balance-corrected events to {output_path}")
        
        return result_df
    
    def _validate_ledger_continuity(self, df: pd.DataFrame) -> None:
        """
        Validate ledger continuity: balance_t = balance_{t-1} + amount_in - amount_out
        """
        logger.info("Validating ledger continuity...")
        
        for cid in df['customer_id'].unique():
            cdf = df[df['customer_id'] == cid].sort_values('timestamp')
            if len(cdf) == 0:
                continue
            
            prev_balance = None
            for row in cdf.itertuples():
                if prev_balance is None:
                    prev_balance = row.balance
                    continue
                
                amount_in = row.amount if row.direction == "inflow" else 0.0
                amount_out = row.amount if row.direction == "outflow" else 0.0
                expected = prev_balance + amount_in - amount_out
                
                if abs(expected - row.balance) > 0.01:  # Allow small floating point errors
                    self.stats.ledger_continuity_failures += 1
                    logger.warning(
                        f"Ledger continuity failure for {cid} at {row.timestamp}: "
                        f"expected {expected:.2f}, got {row.balance:.2f}"
                    )
                
                prev_balance = row.balance
        
        if self.stats.ledger_continuity_failures == 0:
            logger.info("Ledger continuity validation: PASSED")
        else:
            logger.warning(f"Ledger continuity validation: {self.stats.ledger_continuity_failures} failures")
    
    def _log_constraint_stats(self) -> None:
        """Log constraint enforcement statistics."""
        logger.info("=" * 60)
        logger.info("Balance Reconstruction Statistics")
        logger.info("=" * 60)
        logger.info(f"Total transactions: {self.stats.total_transactions}")
        logger.info(f"Accepted transactions: {self.stats.accepted_transactions}")
        logger.info(f"Rejected - Insufficient funds: {self.stats.rejected_insufficient_funds}")
        logger.info(f"Rejected - Tier cap violations: {self.stats.rejected_tier_cap_violation}")
        logger.info(f"Rejected - Daily velocity cap: {self.stats.rejected_daily_velocity_cap}")
        logger.info(f"Ledger continuity failures: {self.stats.ledger_continuity_failures}")
        
        total_rejected = (
            self.stats.rejected_insufficient_funds +
            self.stats.rejected_tier_cap_violation +
            self.stats.rejected_daily_velocity_cap
        )
        acceptance_rate = (self.stats.accepted_transactions / self.stats.total_transactions * 100) if self.stats.total_transactions > 0 else 0
        logger.info(f"Acceptance rate: {acceptance_rate:.2f}%")
        logger.info("=" * 60)
